FROM node:20-slim
ENV http_proxy=http://10.199.15.4:8080
ENV https_proxy=http://10.199.15.4:8080
ENV HTTP_PROXY=http://10.199.15.4:8080
ENV HTTPS_PROXY=http://10.199.15.4:8080
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
EXPOSE 3001
CMD ["npx", "tsx", "src/server.ts"]
