FROM node:20-slim AS builder
ENV http_proxy=http://10.199.15.4:8080
ENV https_proxy=http://10.199.15.4:8080
ENV HTTP_PROXY=http://10.199.15.4:8080
ENV HTTPS_PROXY=http://10.199.15.4:8080
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npx prisma generate
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
